title: Selendroid
org: ebay Software Fondation
encoding: UTF-8
current_version: 0.7.0
selendroid_maven_search_link: http://search.maven.org/#search|ga|1|selendroid
standalone_download_link: https://github.com/selendroid/selendroid/releases/download/0.7.0/selendroid-standalone-0.7.0-with-dependencies.jar
selendroid_test_app_download_link: http://search.maven.org/remotecontent?filepath=io/selendroid/selendroid-test-app/0.7.0/selendroid-test-app-0.7.0.apk
source_repo: https://github.com/selendroid/selendroid
irc_channel: selendroid
mailing_list: http://groups.google.com/group/selendroid
issue_tracker: https://github.com/selendroid/selendroid/issues?direction=desc&sort=updated&state=open
contributors: https://github.com/selendroid/selendroid/blob/master/AUTHORS
setup_page: setup.html
mobile_web_page: mobileWeb.html
native_apps_page: native.html
hybrid_apps_page: hybrid.html
inspector_page: inspector.html
scale_page: scale.html
faq_page: faq.html
architecture_page: architecture.html


profiles:
  development:
    deploy: nil # force development as the default
  production:
    base_url: 'http://selendroid.io'
    google_analytics: UA-1537443-9
    disqus: selendroid
    resolve_published_artifacts: true
    minify: true
    deploy:
      host: github_pages
      branch: master
      repository: upstream
